# Generated by Django 3.2.4 on 2023-12-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('edad', models.IntegerField(db_column='edad')),
                ('domicilio', models.TextField(db_column='Domicilio')),
                ('telefono', models.TextField(db_column='telefono', max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='datos',
            fields=[
                ('idUser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('correo', models.CharField(db_column='correo', max_length=100)),
                ('edad', models.CharField(db_column='edad', max_length=100)),
                ('p1', models.CharField(db_column='pre1', max_length=100)),
                ('p2', models.CharField(db_column='pre2', max_length=100)),
                ('p3', models.CharField(db_column='pre3', max_length=100)),
                ('p4', models.CharField(db_column='pre4', max_length=100)),
                ('p5', models.CharField(db_column='pre5', max_length=100)),
                ('p6', models.CharField(db_column='pre6', max_length=100)),
                ('p7', models.CharField(db_column='pre7', max_length=100)),
                ('p8', models.CharField(db_column='pre8', max_length=100)),
            ],
            options={
                'db_table': 'datos',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('precio', models.CharField(db_column='precio', max_length=100)),
                ('stock', models.CharField(db_column='stock', max_length=100)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('idVehiculo', models.AutoField(db_column='id_vehiculo', primary_key=True, serialize=False)),
                ('modelo', models.CharField(db_column='modelo', max_length=50)),
                ('matricula', models.CharField(db_column='matricula', max_length=50)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id_status', models.AutoField(db_column='id_status', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(db_column='estado', default=False)),
                ('user', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='repartidor',
            fields=[
                ('idRepartidor', models.AutoField(db_column='id_repartidor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('aPaterno', models.CharField(db_column='aPaterno', max_length=100)),
                ('aMaterno', models.CharField(db_column='aMaterno', max_length=100)),
                ('edad', models.IntegerField(db_column='edad')),
                ('correo', models.CharField(db_column='correo', max_length=100, unique=True)),
                ('domicilio', models.TextField(db_column='Domicilio')),
                ('telefono', models.TextField(db_column='telefono', max_length=100)),
                ('curp', models.TextField(db_column='curp', max_length=18)),
                ('nss', models.TextField(db_column='nss', max_length=20)),
                ('idVehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
            ],
            options={
                'db_table': 'repartidor',
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(db_column='fecha_pedido')),
                ('paqueteria', models.CharField(db_column='paqueteria', max_length=100)),
                ('numSeguimiento', models.CharField(db_column='num_seguimiento', max_length=100)),
                ('estado', models.CharField(db_column='estado', max_length=100)),
                ('idCliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='detalle_pedido',
            fields=[
                ('idDetalle', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
